keywords = [
    "bottle",
    "container",
    "vessel",
    "flask",
    "jar",
    "canteen",
    "ampoule",
    "phial",
    "decanter",
    "jug",
    "carafe",
    "vial",
    "receptacle",
    "gourd",
    "pot",
    "vase",
    "pitcher",
    "demijohn",
    "flagon",
    "cruet",
    "urn",
    "growler",
    "ewer",
    "vessel",
    "pottery",
    "bowl",
    "canister",
    "tumbler",
    "cup",
    "mug",
    "glass",
    "beaker",
    "goblet",
    "chalice",
    "wineglass",
    "stemware",
    "drinking vessel",
    "carafe",
    "flacon",
    "receptacle",
    "ampulla",
    "container",
    "holder",
    "repository",
    "package"
]

descriptions = [
    "The bottle is a versatile container that can hold various liquids.",
    "A flask is a compact vessel often used for carrying small amounts of liquid.",
    "The jar is a wide-mouthed container suitable for storing food or other items.",
    "A canteen is a portable water container commonly used during outdoor activities.",
    "An ampoule is a small glass vessel used for storing and preserving liquid substances.",
    "The decanter is an elegant glass container used for serving and aerating wine.",
    "A jug is a large container with a narrow neck and handle, typically used for pouring liquids.",
    "The carafe is a stylish vessel used for serving beverages, such as wine or water.",
    "A vial is a small, cylindrical container used for storing liquid medications or samples.",
    "The gourd is a natural vessel commonly used for carrying water or other liquids.",
    "A pot is a rounded container often used for cooking or storing food.",
    "The vase is an ornamental container typically used for displaying flowers.",
    "A pitcher is a container with a spout used for pouring liquids, such as water or juice.",
    "The demijohn is a large glass container with a narrow neck, often used for fermenting or storing liquids.",
    "A flagon is a large container, usually made of metal or pottery, used for holding and serving drinks.",
    "The cruet is a small container used for dispensing oil, vinegar, or other condiments.",
    "An urn is a decorative container used for holding the ashes of the deceased.",
    "The growler is a sealable glass or ceramic container used for transporting draft beer.",
    "An ewer is a decorative pitcher with a handle, used for holding and pouring liquid.",
    "The pottery vessel is a handmade container crafted from clay or ceramic materials.",
    "A bowl is a round, open container used for holding or serving food.",
    "The canister is a cylindrical container with a lid, often used for storing dry goods or substances.",
    "A tumbler is a flat-bottomed glass or cup without a handle, used for drinking.",
    "The cup is a small open container used for holding liquids, typically with a handle.",
    "A mug is a large, cylindrical cup with a handle, often used for drinking hot beverages.",
    "The glass is a transparent container used for serving and drinking various liquids.",
    "A beaker is a cylindrical container with a flat bottom, often used in scientific experiments.",
    "The goblet is a stemmed drinking vessel with a wide bowl, commonly used for wine or ceremonial purposes.",
    "A chalice is a ceremonial cup, typically used for religious or symbolic purposes.",
    "The wineglass is a stemmed glass with a wide bowl, designed for serving wine.",
    "The stemware refers to a collection of elegant and delicate drinking vessels with long stems.",
    "A drinking vessel is any container specifically designed for holding and consuming liquids.",
    "The carafe is a stylish container used for serving beverages, such as wine or water.",
    "A flacon is a small, decorative bottle used for storing perfumes or essential oils.",
    "The receptacle is a general term for any type of container used for holding or storing things.",
    "An ampulla is a small, flask-like container often used for holding holy water or medicinal liquids.",
    "The container is a generic term referring to any object used for holding or transporting substances.",
    "The holder is a device or object designed to support or contain something.",
    "A repository is a centralized storage or container for keeping things in a systematic manner.",
    "The package is a wrapping or container used for protecting and transporting goods."
]

descriptions = descriptions + ["This is a photo of " + keyword for keyword in keywords]
descriptions = descriptions + ["This is " + keyword for keyword in keywords]