keywords = [
    "cable",
    "wire",
    "cord",
    "line",
    "rope",
    "hawser",
    "strand",
    "thread",
    "string",
    "conductor",
    "lead",
    "cabling",
    "flex",
    "copper",
    "fiber",
    "optical fiber",
    "coaxial",
    "twisted pair",
    "Ethernet",
    "USB",
    "HDMI",
    "power cord",
    "extension cord",
    "network cable",
    "patch cable",
    "data cable",
    "audio cable",
    "video cable",
    "fiber optic cable",
    "LAN cable",
    "telephone cable",
    "CAT5",
    "CAT6",
    "CAT7",
    "RG-6",
    "RG-59",
    "TOSLINK",
    "VGA",
    "DVI",
    "coax",
    "AV cable",
    "composite cable",
    "component cable",
    "XLR cable",
    "balanced cable",
    "unbalanced cable",
    "s-video cable",
    "SCART",
    "firewire",
    "IEEE 1394",
    "serial cable",
    "parallel cable"
]

descriptions = [
    "The cable is an essential component for transmitting signals or electrical power.",
    "A wire is a thin, flexible metallic strand used for conducting electricity or transmitting signals.",
    "A cord is a thick, flexible cable typically used for connecting devices or providing power.",
    "The line refers to a long, narrow cable used for various purposes, such as fishing or telecommunications.",
    "A rope is a strong, thick cable made of twisted or braided strands, commonly used for lifting or securing objects.",
    "The hawser is a large, heavy rope used for towing or mooring ships.",
    "A strand is a single thin piece of wire or fiber used as a component of a larger cable or rope.",
    "The thread is a fine, thin strand of material, often used for sewing or embroidery.",
    "A string is a thin, flexible cord made of multiple strands twisted together, used for various applications.",
    "The conductor is a material or wire that carries electrical current within a cable or circuit.",
    "A lead is a flexible insulated cable used for connecting electronic components or devices.",
    "The cabling refers to the system of cables used for transmitting signals or power in a structured manner.",
    "A flex is a flexible cable commonly used for electrical connections in appliances or machinery.",
    "The copper is a highly conductive metal often used as a core material in electrical cables or wires.",
    "A fiber is an ultra-thin strand of glass or plastic used for transmitting data as light pulses.",
    "The optical fiber is a type of cable that uses light to transmit data over long distances.",
    "A coaxial cable is a type of electrical cable with a central conductor surrounded by an insulating layer and a tubular conducting shield.",
    "The twisted pair is a type of cable used for transmitting signals, consisting of two insulated wires twisted together.",
    "An Ethernet cable is a type of network cable commonly used for wired internet connections.",
    "The USB cable is a standardized cable used for connecting various devices to computers or chargers.",
    "An HDMI cable is a high-definition multimedia interface cable used for transmitting audio and video signals.",
    "The power cord is a cable used to connect an electrical device to a power source.",
    "An extension cord is a long, flexible cable with multiple outlets used for extending the reach of electrical devices.",
    "The network cable is a cable used to connect devices in a computer network.",
    "A patch cable is a short cable used to connect electronic devices or network components.",
    "The data cable is a cable designed for transmitting data between devices.",
    "An audio cable is a cable used for transmitting audio signals between devices or components.",
    "The video cable is a cable used for transmitting video signals between devices or components.",
    "A fiber optic cable is a cable that uses optical fibers to transmit data as light signals.",
    "The LAN cable is a cable used for connecting devices in a local area network (LAN).",
    "A telephone cable is a cable used for transmitting telephone signals or connecting telephones.",
    "The CAT5 cable is a type of network cable commonly used for Ethernet connections.",
    "A CAT6 cable is an improved version of the CAT5 cable, offering higher performance for network connections.",
    "The CAT7 cable is a high-speed network cable designed for transmitting data at high speeds.",
    "An RG-6 cable is a type of coaxial cable commonly used for cable television and satellite signals.",
    "The RG-59 cable is a thinner version of the RG-6 cable, often used for short-distance video applications.",
    "A TOSLINK cable is an optical audio cable used for transmitting digital audio signals between devices.",
    "The VGA cable is an analog video cable used for connecting computers to displays.",
    "A DVI cable is a digital video cable used for transmitting high-quality video signals.",
    "The coax cable is a coaxial cable used for various applications, including television and data transmission.",
    "An AV cable is an audio/video cable used for connecting audio and video devices.",
    "The composite cable is a type of AV cable that combines multiple audio and video signals into a single cable.",
    "A component cable is an analog video cable used for transmitting high-quality video signals.",
    "The XLR cable is a balanced audio cable commonly used in professional audio systems.",
    "A balanced cable is an audio cable designed to minimize noise and interference in audio signals.",
    "An unbalanced cable is an audio cable that carries audio signals with a single conductor and ground connection.",
    "The s-video cable is a video cable used for transmitting analog video signals.",
    "A SCART cable is a type of AV cable commonly used in Europe for connecting audiovisual equipment.",
    "The FireWire cable, also known as IEEE 1394, is a high-speed serialcable used for connecting devices such as cameras and external storage devices.",
    "A serial cable is a cable used for transmitting data between devices in a serial communication protocol.",
    "The parallel cable is a cable used for transmitting data in parallel, often used for connecting printers or scanners."
]
descriptions = descriptions + ["This is a photo of " + keyword for keyword in keywords]
descriptions = descriptions + ["This is " + keyword for keyword in keywords]