keywords = [
    "capsule",
    "pill",
    "tablet",
    "caplet",
    "gelcap",
    "cap",
    "encapsulation",
    "casing",
    "shell",
    "container",
    "case",
    "vial",
    "ampule",
    "ampoule",
    "tube",
    "cylinder",
    "enclosement",
    "envelope",
    "wrapper",
    "enclosure",
    "covering",
    "housing",
    "sheath",
    "sleeve",
    "wrapper",
    "packet"
]

descriptions = [
    "The capsule is a small medical form for oral consumption, typically containing medication.",
    "A pill is a solid, round form of medication that is swallowed.",
    "A tablet is a flat, rectangular form of medication that is swallowed.",
    "The caplet is a tablet-shaped form of medication with a coating that makes it easier to swallow.",
    "A gelcap is a capsule filled with liquid or gel medication.",
    "The cap is the cover or top part of a container or object.",
    "Encapsulation refers to the process of enclosing something in a capsule or protective covering.",
    "The casing is the outer shell or cover of an object or device.",
    "A shell is a rigid outer covering or structure that provides protection or containment.",
    "A container is a receptacle or vessel used for holding or storing something.",
    "The case is a box or container used for protecting or transporting items.",
    "A vial is a small glass or plastic container used for storing liquids, such as medication or samples.",
    "An ampule is a small sealed glass container used for holding a single dose of medication.",
    "An ampoule is a small sealed glass container used for holding a single dose of medication.",
    "A tube is a long, hollow cylindrical object used for holding or dispensing substances.",
    "The cylinder is a solid or hollow geometric shape with two parallel circular bases.",
    "An enclosement is a structure or container that completely surrounds or encloses something.",
    "An envelope is a flat, usually rectangular paper container used for enclosing letters or documents.",
    "A wrapper is a covering material used to enclose or protect something.",
    "An enclosure is a structure or container that surrounds or encloses something.",
    "The covering is a layer or material that conceals or protects something.",
    "The housing is a rigid outer structure or case that encloses and protects internal components.",
    "A sheath is a protective covering or casing that encloses or fits closely around something.",
    "A sleeve is a cylindrical or tubular covering that fits around or over something.",
    "A wrapper is a covering material used to enclose or protect something.",
    "A packet is a small, usually flat container or package used for holding or enclosing items."
]
descriptions = descriptions + ["This is a photo of " + keyword for keyword in keywords]
descriptions = descriptions + ["This is " + keyword for keyword in keywords]