keywords = [
    "hazelnut",
    "filbert",
    "cobnut",
    "Hazel nut",
    "Hazel",
    "nut",
    "tree nut",
    "brown nut",
    "round nut",
    "edible nut",
    "kernel",
    "seed",
    "bush nut",
    "collar nut",
    "lamb's tail",
    "cob",
    "cob's nut",
    "Lambert's nut",
    "Roman nut",
    "Lamberts",
    "filbert nut",
    "cobble",
    "cob nut",
    "Abellana",
    "avellana",
    "noisette"
]

descriptions = [
    "The hazelnut is a versatile and delicious nut that adds a delightful crunch to baked goods.",
    "Enjoy the rich and buttery flavor of filbert nuts in your favorite desserts and confections.",
    "Cobnuts, also known as cobble, are a popular variety of hazelnuts used in snacks and desserts.",
    "Hazel nuts, also referred to as round nuts, are a nutritious and tasty addition to salads and trail mixes.",
    "The lamb's tail, a synonym for hazelnut, is a small and flavorful nut often used in baking.",
    "Discover the natural sweetness and texture of hazelnut butter made from roasted hazel nuts.",
    "The Roman nut, also called Lambert's nut, is a type of hazelnut with a rich and nutty taste.",
    "Indulge in the creamy and velvety flavor of hazelnut-infused coffee for a delightful morning treat.",
    "Seed your favorite recipes with hazelnuts to add a satisfying crunch and earthy flavor.",
    "The bush nut, another term for hazelnut, is a versatile ingredient in both sweet and savory dishes.",
    "Enjoy the natural goodness of hazelnuts, a nutritious tree nut packed with vitamins and minerals.",
    "The collar nut, or hazelnut, is a popular ingredient in pralines and other delicious confections.",
    "Savor the aroma and taste of roasted hazelnuts, a perfect snack for any time of the day.",
    "The cobnut, also known as cob nut, is a crunchy and delicious nut that complements various dishes.",
    "Hazel, a synonym for hazelnut, is a versatile nut used in desserts, spreads, and savory recipes.",
    "Add a sprinkle of chopped hazelnuts to your salads for an extra layer of texture and nutty flavor.",
    "Enjoy the rich and smooth flavor of hazelnut chocolate, a delightful treat for chocolate lovers.",
    "The cob's nut, another name for hazelnut, is a key ingredient in traditional British desserts.",
    "Lamberts, also known as hazelnuts, are often used in baking and confectionery for their distinct taste.",
    "Experiment with hazelnut flour, a gluten-free alternative that adds a nutty flavor to baked goods.",
    "Experience the nutty and aromatic taste of roasted hazelnut oil in your salad dressings and marinades.",
    "The hazel nut, or Abellana, is a versatile ingredient that enhances the flavor of both sweet and savory dishes.",
    "Enjoy the delightful combination of hazelnut and chocolate in a decadent hazelnut spread.",
    "Noisette, a French term for hazelnut, adds a delightful crunch and flavor to pastries and desserts.",
    "The brown nut, also known as hazelnut, is a versatile ingredient widely used in culinary creations.",
    "Cobble, or cob nut, is a delicious and nutritious nut that can be enjoyed on its own or in recipes.",
    "Try hazelnut milk as a dairy-free alternative with a creamy texture and a hint of nutty sweetness.",
    "Avellana, another name for hazelnut, is commonly used in Mediterranean cuisine for its distinct flavor.",
    "The edible nut, or hazelnut, is a healthy snack packed with protein, fiber, and essential nutrients."
]
descriptions = descriptions + ["This is a photo of " + keyword for keyword in keywords]
descriptions = descriptions + ["This is " + keyword for keyword in keywords]