keywords = [
    "leather",
    "hide",
    "skin",
    "pelt",
    "rawhide",
    "animal skin",
    "cowhide",
    "sheepskin",
    "goatskin",
    "pigskin",
    "suede",
    "buff",
    "shagreen",
    "patent leather",
    "nappa",
    "buckskin",
    "morocco",
    "calfskin",
    "top-grain leather",
    "genuine leather",
    "faux leather",
    "synthetic leather",
    "vinyl",
    "pleather",
    "artificial leather",
    "imitation leather"
]

descriptions = [
    "The soft and supple texture of leather makes it a popular choice for luxurious handbags.",
    "Explore the durability and timeless elegance of cowhide leather in fashion and interior design.",
    "Suede, a type of leather with a velvety touch, adds a touch of sophistication to clothing and accessories.",
    "Step out in style with patent leather shoes that offer a glossy and polished look.",
    "Genuine leather provides a natural and authentic feel, perfect for crafting high-quality wallets.",
    "Faux leather, also known as synthetic leather, offers a cruelty-free alternative with a similar look and feel.",
    "Discover the versatility of top-grain leather, known for its durability and smooth finish.",
    "Embrace the rustic charm of buckskin leather, often used in the creation of traditional garments.",
    "Nappa leather, prized for its softness and flexibility, is commonly used in luxury automotive interiors.",
    "Add a touch of luxury to your living space with a leather sofa that exudes comfort and style.",
    "Experience the timeless beauty of morocco leather, often used for bookbinding and luxury goods.",
    "Calfskin leather, known for its fine grain and softness, is a popular choice for premium footwear.",
    "The texture and durability of rawhide leather make it ideal for crafting sturdy dog chew toys.",
    "Sheepskin, with its plush and cozy feel, is commonly used to create warm and comfortable winter boots.",
    "Shagreen, a type of textured leather, adds a unique and exotic touch to accessories and home decor.",
    "Vinyl, a synthetic material resembling leather, offers a cost-effective option for upholstery and fashion.",
    "Pleather, short for 'plastic leather,' is an artificial leather alternative that is vegan-friendly.",
    "Artificial leather, also known as imitation leather, provides an affordable and cruelty-free option.",
    "The rich texture and durability of pigskin leather make it a popular choice for football and baseball gloves.",
    "Leather jackets have been a timeless fashion staple, symbolizing rebellion and effortless style.",
    "The tanning process transforms rawhide into leather, preserving it for various practical and aesthetic uses.",
    "Leatherworking is a skilled craft that involves cutting, stitching, and shaping leather to create functional and decorative items.",
    "Leather goods, such as belts, wallets, and bags, are cherished for their durability and classic appeal.",
    "Leather care involves regular cleaning and conditioning to maintain its suppleness and extend its lifespan.",
    "Leather craftsmanship has a long history, dating back to ancient civilizations that utilized animal hides for protection and clothing.",
    "The aroma of genuine leather evokes a sense of luxury and craftsmanship, enhancing the overall experience of leather products.",
    "Leather accessories, such as keychains and bracelets, add a touch of sophistication to everyday outfits.",
    "Leather upholstery provides a luxurious and comfortable seating option for furniture, adding a touch of elegance to any space."
]
descriptions = descriptions + ["This is a photo of " + keyword for keyword in keywords]
descriptions = descriptions + ["This is " + keyword for keyword in keywords]