keywords = [
    "metal nut",
    "fastener",
    "screw nut",
    "bolt nut",
    "hex nut",
    "wing nut",
    "lock nut",
    "nylon insert nut",
    "flange nut",
    "cap nut",
    "jam nut",
    "cage nut",
    "coupling nut",
    "T-nut",
    "rivet nut",
    "blind nut",
    "castle nut",
    "slotted nut",
    "square nut",
    "self-locking nut",
    "acorn nut",
    "barrel nut",
    "compression nut",
    "cross dowel nut",
    "insert nut",
    "knurled nut",
    "weld nut",
    "spring nut",
    "tee nut",
    "panel nut",
    "thumb nut",
    "wire nut",
    "split nut",
    "captive nut",
    "jam lock nut",
    "swage nut",
    "welding nut",
    "domed cap nut",
    "high nut",
    "low nut",
    "slip-on lock nut",
    "wing lock nut",
    "self-aligning nut",
    "flanged lock nut",
    "reduced hex nut",
    "thin nut",
    "wing cap nut"
]

descriptions = [
    "A metal nut is a type of fastener commonly used to secure objects together.",
    "The hex nut, also known as a hexagon nut, is a six-sided metal nut used with bolts and screws.",
    "A wing nut is a type of metal nut with two wings that can be easily tightened or loosened by hand.",
    "Lock nuts are designed to prevent loosening under vibrations or torque, providing added security.",
    "The nylon insert nut features a nylon ring inside the metal nut to create a locking effect when tightened.",
    "Flange nuts have a wide circular base, providing a larger surface area for distributing pressure and reducing the risk of damage.",
    "Cap nuts, also called acorn nuts, have a rounded top resembling an acorn and are often used for aesthetic purposes.",
    "Jam nuts are thin metal nuts used in conjunction with another nut to prevent loosening.",
    "T-nuts, also known as tee nuts, have a T-shaped body that is inserted into a pre-drilled hole to create a threaded connection.",
    "Rivet nuts, also called blind nuts, are internally threaded metal nuts that can be installed without access to the backside of the material.",
    "The castle nut, named for its resemblance to a castle turret, is used with a cotter pin to secure rotating components.",
    "Square nuts have a square shape and are commonly used with square-headed bolts or in applications requiring a wrench.",
    "Self-locking nuts, such as nylon lock nuts, feature a built-in locking mechanism that helps prevent loosening due to vibrations or torque.",
    "Barrel nuts, also known as connector nuts, are cylindrical metal nuts used to connect two or more objects together.",
    "Spring nuts, also called speed nuts, have spring-loaded threads that allow for quick installation and provide a secure grip.",
    "Wire nuts, often used in electrical applications, are metal nuts with an inner cavity designed to connect and secure multiple wires together.",
    "Captive nuts are permanently attached to a separate component, making them convenient for assembly and disassembly.",
    "Swage nuts, commonly used in aerospace and automotive industries, have a swaged body that provides a secure grip in thin materials.",
    "A welding nut is specifically designed for welding onto another object, providing a threaded connection.",
    "High nuts, also known as tall nuts, have an increased height to provide extra clearance or to extend the threaded portion.",
    "Low nuts, also called short nuts, have a reduced height compared to standard nuts, ideal for applications with limited space.",
    "The wing lock nut features a locking mechanism along with wings for easy installation and removal by hand.",
    "Self-aligning nuts have a spherical or conical shape that allows them to align with misaligned or angled surfaces.",
    "Thin nuts, as the name suggests, have a thinner profile and are suitable for applications with limited thread engagement.",
    "Slip-on lock nuts, also known as prevailing torque nuts, have a locking feature that increases resistance to loosening.",
    "The cross dowel nut is a specialized nut with a perpendicular hole, often used in furniture assembly.",
    "Insert nuts, also called threaded inserts, are used to create threads in wood, plastic, or other soft materials.",
    "Knurled nuts have a textured outer surface, allowing for easy gripping and tightening by hand.",
    "Panel nuts, also known as jam lock nuts, are used to secure panels or plates in place.",
    "Thumb nuts have a wing-like projection that allows for easy tightening and loosening by hand, without the need for tools.",
    "Split nuts, also called split-ring nuts, have a split design that allows them to be easily installed or removed from a threaded rod.",
    "The jam lock nut is designed to be tightened against another nut to prevent loosening in high-vibration environments.",
    "A domed cap nut, also known as an acorn cap nut, features a domed top for a finished appearance and added protection.",
    "The slip-on lock nut, also called a prevailing torque nut, provides resistance to loosening caused by vibration or torque.",
    "The wing cap nut combines the features of a wing nut and a cap nut, providing both easy hand tightening and a finished appearance.",
    "The flanged lock nut, also known as a serrated flange nut, has a built-in washer-like flange that helps distribute pressure and prevent loosening.",
    "The reduced hex nut, also called a thin height hex nut, has a lower profile compared to standard hex nuts, useful in applications with limited space.",
    "The self-locking nut, also known as a prevailing torque nut, incorporates a locking feature to resist loosening caused by vibration or torque.",
    "The blind nut, also called a rivet nut or threaded insert, allows for a threadedconnection in materials where access to the backside is limited.",
    "A metal nut is a versatile fastening component used in various industries such as construction, automotive, and manufacturing.",
    "Metal nuts come in a wide range of sizes, materials, and designs, offering flexibility for different applications and requirements.",
    "Whether it's securing machinery, assembling furniture, or connecting electrical components, metal nuts play a crucial role in ensuring structural integrity and stability.",
    "From standard nuts like hex nuts and wing nuts to specialized variants like weld nuts and spring nuts, there is a metal nut for every specific need.",
    "Metal nuts are often made from materials like steel, stainless steel, brass, or aluminum, chosen based on factors such as strength, corrosion resistance, and environmental conditions.",
    "The selection of the right metal nut is essential to achieve optimal performance, reliability, and safety in various mechanical and structural systems.",
    "Metal nuts are typically used in conjunction with bolts, screws, or threaded rods to create a secure and adjustable connection.",
    "The proper tightening of metal nuts is crucial to ensure the desired clamping force and prevent over-tightening or under-tightening.",
    "Some metal nuts, like lock nuts and self-locking nuts, provide additional resistance against loosening due to external forces or vibrations.",
    "Metal nuts are often categorized based on their shape, purpose, or installation method, allowing for easy identification and selection in different applications.",
    "The durability and longevity of metal nuts make them a cost-effective solution for long-term use, reducing the need for frequent replacements or repairs.",
    "Metal nuts are widely used in automotive manufacturing, aerospace engineering, electrical installations, plumbing systems, and many other industries.",
    "Metal nuts are essential components in the assembly of structures, machinery, appliances, and various mechanical systems, ensuring stability and functionality.",
    "Proper storage and handling of metal nuts are important to prevent rusting, contamination, or damage that could compromise their performance.",
    "Metal nuts are often subjected to rigorous quality control measures, including dimensional checks, material testing, and torque resistance assessments.",
    "The design and engineering of metal nuts continue to evolve, with advancements aimed at improving strength, ease of use, and overall performance.",
    "Metal nuts, despite their small size, play a crucial role in the overall safety and reliability of structures, equipment, and systems.",
    "Metal nuts are widely available in hardware stores, industrial suppliers, and online retailers, making them easily accessible for various projects and applications.",
    "Metal nuts are an integral part of the hardware and fastening industry, providing essential solutions for joining, securing, and adjusting components.",
    "Metal nuts are used in a wide range of applications, from simple household repairs to complex industrial installations, demonstrating their versatility and importance.",
    "The use of metal nuts in construction and engineering projects dates back centuries, showcasing their enduring functionality and relevance.",
    "Metal nuts are often designed to comply with industry standards and specifications, ensuring compatibility and interchangeability across different manufacturers and systems."
]
descriptions = descriptions + ["This is a photo of " + keyword for keyword in keywords]
descriptions = descriptions + ["This is " + keyword for keyword in keywords]