keywords = [
    "pill",
    "tablet",
    "capsule",
    "medication",
    "medicine",
    "drug",
    "prescription",
    "pharmaceutical",
    "remedy",
    "dose",
    "potion",
    "supplement",
    "vitamin",
    "antibiotic",
    "antidepressant",
    "painkiller",
    "analgesic",
    "sedative",
    "tranquilizer",
    "antihistamine",
    "diuretic",
    "antacid",
    "steroid",
    "antipyretic",
    "anticoagulant",
    "antifungal",
    "antiviral",
    "antiemetic",
    "antidiarrheal",
    "anti-inflammatory",
    "antiseptic",
    "antiemetic",
    "anticonvulsant",
    "antihypertensive",
    "antidepressant",
    "antipsychotic",
    "antianxiety",
    "stimulant",
    "sleeping pill",
    "birth control pill",
    "diet pill",
    "morning-after pill",
    "placebo"
]

descriptions = [
    "The doctor prescribed a pill to alleviate my headache.",
    "She carefully swallowed a capsule with a glass of water.",
    "The pharmacist dispensed the medication in the form of a tablet.",
    "He relied on a painkiller to relieve his chronic back pain.",
    "I take a daily supplement to ensure I get all the necessary vitamins.",
    "The antibiotic helped fight off the infection.",
    "She relied on the antihistamine to alleviate her allergy symptoms.",
    "The tranquilizer helped calm his nerves before the flight.",
    "The diuretic was prescribed to reduce fluid retention.",
    "He relied on an antacid to relieve his heartburn.",
    "The doctor prescribed a steroid to reduce inflammation.",
    "The anticoagulant helped prevent blood clots.",
    "She used an antifungal cream to treat the infection.",
    "He took an antiviral medication to combat the flu.",
    "She relied on an antiemetic to alleviate her nausea.",
    "The antiseptic helped clean and disinfect the wound.",
    "He took an anticonvulsant to manage his seizures.",
    "She relied on an antihypertensive to control her blood pressure.",
    "The antidepressant helped improve his mood and overall well-being.",
    "He relied on an antipsychotic to manage his symptoms of schizophrenia.",
    "She took an antianxiety medication to reduce her anxiety levels.",
    "The stimulant helped improve his focus and concentration.",
    "She relied on sleeping pills to overcome her insomnia.",
    "The birth control pill provided reliable contraception.",
    "He took a diet pill to aid in his weight loss journey.",
    "She relied on the morning-after pill as a form of emergency contraception.",
    "The placebo was given as part of the control group in the clinical trial."
]
descriptions = descriptions + ["This is a photo of " + keyword for keyword in keywords]
descriptions = descriptions + ["This is " + keyword for keyword in keywords]