keywords = [
    "screw",
    "bolt",
    "fastener",
    "nail",
    "peg",
    "rivet",
    "pin",
    "spike",
    "stud",
    "anchor",
    "hook",
    "clasp",
    "latch",
    "clip",
    "clamp",
    "bracket",
    "hinge",
    "wrench",
    "spanner",
    "pliers"
]

descriptions = [
    "The sturdy bolt secured the heavy metal plate in place.",
    "She hammered the nail into the wall to hang a picture frame.",
    "The carpenter used a peg to join the wooden planks together.",
    "The metal rivet held the two pieces of leather firmly in place.",
    "He inserted the pin into the hinge to create a movable joint.",
    "The spike was driven into the ground to anchor the tent securely.",
    "She used a hook to hang her coat on the back of the door.",
    "The clasp on the necklace ensured it stayed securely around her neck.",
    "He closed the latch on the gate to keep it from swinging open.",
    "She secured the papers together with a clip to keep them organized.",
    "The clamp held the pieces of wood tightly while the glue dried.",
    "The bracket provided support for the shelf on the wall.",
    "The door swung smoothly on its hinges.",
    "He tightened the nut with a wrench to secure the bolt in place.",
    "She adjusted the spanner to fit the size of the nut.",
    "The pliers were used to grip and twist the wire.",
    "A screwdriver is a versatile tool used to tighten or loosen screws.",
    "The hinge allowed the door to swing open and closed.",
    "He used a wrench to tighten the bolt securely.",
    "The spanner was necessary to loosen the stubborn nut.",
    "She used pliers to grip and twist the metal wire.",
    "The sturdy bolt secured the heavy metal plate in place.",
    "She hammered the nail into the wall to hang a picture frame.",
    "The carpenter used a peg to join the wooden planks together.",
    "The metal rivet held the two pieces of leather firmly in place.",
    "He inserted the pin into the hinge to create a movable joint.",
    "The spike was driven into the ground to anchor the tent securely.",
    "She used a hook to hang her coat on the back of the door.",
    "The clasp on the necklace ensured it stayed securely around her neck.",
    "He closed the latch on the gate to keep it from swinging open.",
    "She secured the papers together with a clip to keep them organized.",
    "The clamp held the pieces of wood tightly while the glue dried.",
    "The bracket provided support for the shelf on the wall.",
    "The door swung smoothly on its hinges.",
    "He tightened the nut with a wrench to secure the bolt in place.",
    "She adjusted the spanner to fit the size of the nut.",
    "The pliers were used to grip and twist the wire."
]
descriptions = descriptions + ["This is a photo of " + keyword for keyword in keywords]
descriptions = descriptions + ["This is " + keyword for keyword in keywords]