keywords = [
    "tile",
    "slab",
    "brick",
    "paver",
    "block",
    "stone",
    "panel",
    "plate",
    "shingle",
    "slate",
    "flagstone",
    "cinder",
    "concrete",
    "ceramic",
    "terracotta",
    "porcelain",
    "marble",
    "granite",
    "quartz",
    "limestone",
    "travertine",
    "onyx",
    "sandstone",
    "quarry",
    "mosaic",
    "tessera",
    "glass",
    "mirror",
    "metal",
    "steel",
    "aluminum",
    "copper",
    "bronze",
    "brass",
    "zinc",
    "wood",
    "bamboo",
    "cork",
    "linoleum",
    "vinyl",
    "laminate",
    "parquet",
    "herringbone",
    "hexagon",
    "subway",
    "terrazzo",
    "encaustic",
    "ceramic",
    "porcelain",
    "mosaic",
    "pebble",
    "terracotta",
    "quarry",
    "penny",
    "glass",
    "metal",
    "marble",
    "granite",
    "travertine",
    "slate",
    "limestone",
    "flagstone",
    "wood",
    "cork",
    "linoleum",
    "vinyl",
    "laminate",
    "parquet"
]

descriptions = [
    "The ceramic tile floor in the kitchen was easy to clean.",
    "They used stone slabs to create a beautiful patio.",
    "The brick wall added a rustic charm to the garden.",
    "The porcelain tile shower had an elegant design.",
    "She walked across the wooden parquet floor in her socks.",
    "The mosaic tiles formed an intricate pattern on the bathroom wall.",
    "They installed glass tiles as a backsplash in the kitchen.",
    "The metal plate was used to cover the gap in the flooring.",
    "The terracotta tiles gave the room a warm and earthy feel.",
    "He placed a mirror tile on the wall to create the illusion of a larger space.",
    "The subway tiles in the bathroom were arranged in a classic brick pattern.",
    "She chose a herringbone pattern for the ceramic tile installation.",
    "The granite countertop added a touch of luxury to the kitchen.",
    "The cork flooring provided excellent insulation and cushioning.",
    "They opted for vinyl tiles in the basement for easy maintenance.",
    "The laminate flooring resembled the look of real hardwood.",
    "The hexagon tiles on the bathroom floor created a unique and modern design.",
    "The terrazzo tiles in the hallway had colorful specks embedded in them.",
    "The encaustic tiles on the stairs added a vibrant and artistic touch.",
    "The mosaic tiles on the patio were made of colorful tesserae.",
    "They used pebble tiles in the shower to create a natural and spa-like atmosphere.",
    "The terracotta tiles in the courtyard were sourced from a local quarry.",
    "She admired the penny tiles on the bathroom wall, creating a mosaic of small copper coins.",
    "The glass tiles on the kitchen backsplash reflected the light beautifully.",
    "He installed metal tiles on the fireplace surround for a modern and sleek look.",
    "The marble tiles in the foyer exuded elegance and sophistication.",
    "The granite tiles in the bathroom added durability and a touch of luxury.",
    "The slate tiles on the patio were resistant to weather and provided a natural look.",
    "The limestone tiles in the living room had a soft and earthy tone.",
    "They used flagstone tiles to create a rustic pathway in the garden.",
    "The wooden tiles on the deck created a warm and inviting outdoor space.",
    "She appreciated the natural beauty of the cork flooring in the eco-friendly house.",
    "The vinyl tiles in the basement were easy to install and maintain.",
    "They selected laminate tiles that resembled the look of real hardwood flooring.",
    "The parquet tiles in the ballroom formed an intricate geometric pattern.",
    "The herringbone tiles in the hallway added a touch of elegance and style.",
    "The hexagon tiles in the bathroom created a modern and trendy design.",
    "The subway tiles on the kitchen walls gave a timeless and classic look.",
    "The terrazzo tiles in the restaurant had unique and colorful patterns.",
    "The encaustic tiles on the patio added a vibrant and artistic touch.",
    "The mosaic tiles on the shower floor were made of small pebbles.",
    "The terracotta tiles in the courtyard were sourced from a local quarry.",
    "She admired the glass tiles on the bathroom walls, creating a stunning visual effect.",
    "He installed metal tiles on the kitchen backsplash for a sleek and contemporary look.",
    "The marble tiles in the bathroom exuded luxury and sophistication.",
    "The granite tiles in the kitchen provided a durable and beautiful countertop.",
    "The slate tiles on the outdoor patio offered a natural and textured surface.",
    "The limestone tiles in the living room gave a warm and inviting ambiance.",
    "They used flagstone tiles to create a charming and rustic pathway in the garden.",
    "The wooden tiles on the bedroom floor created a cozy and natural atmosphere.",
    "She appreciated the environmentally-friendly cork flooring in her home office.",
    "The vinyl tiles in the basement provided a practical and low-maintenance solution.",
    "They chose laminate tiles for the hallway that resembled the look of hardwood.",
    "The parquet tiles in the dining room showcased an elegant and intricate design.",
    "The herringbone tiles in the bathroom added a touch of sophistication and style.",
    "The hexagon tiles in the kitchen created a trendy and contemporary look.",
    "The subway tiles on the bathroom walls offered a timeless and clean aesthetic.",
    "The terrazzo tiles in the restaurant had eye-catching patterns and colors.",
    "The encaustic tiles on the patio brought an artistic and lively atmosphere.",
    "The mosaic tiles on the bathroom floor had a captivating pattern of small stones.",
    "The terracotta tiles in the courtyard were sourced from a local quarry.",
    "She admired the glass tiles on the kitchen backsplash,creating a stunning focal point in the room.",
    "He installed metal tiles on the fireplace surround, adding a modern and industrial touch.",
    "The marble tiles in the bathroom gave a luxurious and elegant feel.",
    "The granite tiles in the kitchen provided a durable and stylish countertop.",
    "The slate tiles on the patio created a natural and earthy outdoor space.",
    "The limestone tiles in the living room added a touch of warmth and sophistication.",
    "They used flagstone tiles to create a charming and rustic pathway in the garden.",
    "The wooden tiles on the deck created a cozy and inviting outdoor area.",
    "She appreciated the comfort and eco-friendliness of the cork flooring in her home.",
    "The vinyl tiles in the basement were easy to clean and maintain.",
    "They opted for laminate tiles that resembled the look of real hardwood flooring.",
    "The parquet tiles in the hallway showcased an intricate and timeless design.",
    "The herringbone tiles in the bathroom added a touch of elegance and visual interest.",
    "The hexagon tiles in the kitchen created a modern and stylish focal point.",
    "The subway tiles on the bathroom walls gave a classic and clean look.",
    "The terrazzo tiles in the restaurant had unique and artistic patterns.",
    "The encaustic tiles on the patio added a vibrant and lively atmosphere.",
    "The mosaic tiles on the shower floor provided a comfortable and slip-resistant surface.",
    "The terracotta tiles in the courtyard were sourced locally, adding a touch of authenticity.",
    "She admired the glass tiles on the kitchen backsplash, reflecting light beautifully.",
    "He installed metal tiles on the bathroom wall, creating a contemporary and sleek design.",
    "The marble tiles in the foyer added a touch of luxury and sophistication.",
    "The granite tiles in the kitchen offered a durable and stylish countertop.",
    "The slate tiles on the patio provided a natural and textured outdoor flooring.",
    "The limestone tiles in the living room created a warm and inviting ambiance.",
    "They used flagstone tiles to create a rustic and charming garden pathway.",
    "The wooden tiles on the deck gave a cozy and natural feel to the outdoor space.",
    "She appreciated the eco-friendly and comfortable cork flooring in her home office.",
    "The vinyl tiles in the basement were easy to install and maintain.",
    "They selected laminate tiles that resembled the look of real hardwood flooring.",
    "The parquet tiles in the dining room showcased an elegant and intricate pattern.",
    "The herringbone tiles in the bathroom added a touch of sophistication and style.",
    "The hexagon tiles in the kitchen created a modern and trendy design.",
    "The subway tiles on the bathroom walls offered a timeless and clean aesthetic.",
    "The terrazzo tiles in the restaurant had unique and eye-catching patterns.",
    "The encaustic tiles on the patio brought an artistic and lively atmosphere.",
    "The mosaic tiles on the bathroom floor had a captivating pattern of small stones.",
    "The terracotta tiles in the courtyard were sourced from a local quarry.",
    "She admired the glass tiles on the kitchen backsplash, creating a stunning visual effect.",
    "He installed metal tiles on the fireplace surround for a sleek and contemporary look.",
    "The marble tiles in the bathroom exuded luxury and sophistication.",
    "The granite tiles in the kitchen provided a durable and beautiful countertop.",
    "The slate tiles on the outdoor patio offered a natural and textured surface.",
    "The limestone tiles in the living room gave a warm and inviting ambiance.",
    "They used flagstone tiles to create a rustic pathway in the garden.",
    "The wooden tiles on the deck created a cozy and inviting outdoor space.",
    "She appreciated the environmentally-friendly cork flooring in her home office.",
    "The vinyl tiles in the basement provided a practical and low-maintenance solution.",
    "They chose laminate tiles for the hallway that resembled the look of hardwood.",
    "The parquet tiles in the dining room showcased an elegant and intricate design.",
    "The herringbone tiles in the bathroom added a touch of sophistication and style.",
    "The hexagon tiles in the kitchen created a trendy and contemporary look.",
    "The subway tiles on the bathroom walls offered a timeless and clean aesthetic.",
    "The terrazzo tiles in the restaurant had eye-catching patterns and colors.",
    "The encaustic tiles on the patio brought an artistic and lively atmosphere.",
    "The mosaic tiles on the bathroom floor had a captivating pattern of small stones.",
    "The terracotta tiles in the courtyard were sourced from a local quarry.",
    "She admired the glass tiles on the kitchen backsplash, creating a stunning focal point.",
    "He installed metal tiles on the fireplace surround, adding a modern and industrial touch.",
    "The marble tiles in the bathroom gave a luxurious and elegant feel.",
    "The granite tiles in the kitchen provided a durable and stylish countertop.",
]
descriptions = descriptions + ["This is a photo of " + keyword for keyword in keywords]
descriptions = descriptions + ["This is " + keyword for keyword in keywords]