keywords = [
    "toothbrush",
    "tooth cleaner",
    "dental brush",
    "teeth brush",
    "tooth scrubber",
    "dental scrubber",
    "teeth cleaner",
    "oral brush",
    "mouth brush",
    "tooth polisher",
    "dental polisher",
    "teeth polisher",
    "tooth implement",
    "dental implement",
    "teeth implement",
    "tooth tool",
    "dental tool",
    "teeth tool",
    "tooth bristle",
    "dental bristle",
    "teeth bristle",
    "tooth grooming tool",
    "dental grooming tool",
    "teeth grooming tool",
    "tooth cleaning instrument",
    "dental cleaning instrument",
    "teeth cleaning instrument",
    "tooth brushing device",
    "dental brushing device",
    "teeth brushing device",
    "tooth hygiene tool",
    "dental hygiene tool",
    "teeth hygiene tool",
    "tooth care implement",
    "dental care implement",
    "teeth care implement",
    "tooth hygiene instrument",
    "dental hygiene instrument",
    "teeth hygiene instrument",
    "tooth cleaning brush",
    "dental cleaning brush",
    "teeth cleaning brush",
    "tooth care tool",
    "dental care tool",
    "teeth care tool",
    "tooth hygiene brush",
    "dental hygiene brush",
    "teeth hygiene brush",
    "tooth cleaning utensil",
    "dental cleaning utensil",
    "teeth cleaning utensil",
    "tooth care utensil",
    "dental care utensil",
    "teeth care utensil",
    "tooth hygiene utensil",
    "dental hygiene utensil",
    "teeth hygiene utensil",
    "tooth cleaning bristle",
    "dental cleaning bristle",
    "teeth cleaning bristle",
    "tooth care bristle",
    "dental care bristle",
    "teeth care bristle",
]

descriptions = [
    "A toothbrush is an oral hygiene tool used for cleaning the teeth.",
    "The dental implement, known as a tooth cleaner, is essential for maintaining oral hygiene.",
    "Teeth brushing devices such as the tooth scrubber and dental polisher help keep your mouth clean.",
    "Toothbrushes with bristles are commonly used to remove plaque and food particles.",
    "Using a dental scrubber and teeth implement helps maintain good oral health.",
    "A tooth hygiene brush is a vital tool for maintaining dental care.",
    "Teeth cleaning brushes, like the tooth care utensils, are used to keep the mouth fresh.",
    "Tooth grooming tools, such as the dental tool, aid in maintaining healthy teeth and gums.",
    "Dental hygiene instruments, like the teeth cleaning bristle, are essential for oral care.",
    "Tooth implement, dental hygiene utensil, and teeth care implement are used for oral hygiene routines.",
    "A tooth cleaning brush, along with dental care utensils, ensures proper oral hygiene.",
    "Dental cleaning instruments, like the teeth hygiene brush, are important for maintaining oral health.",
    "Tooth polisher and dental grooming tools are used to keep teeth clean and shiny.",
    "Teeth cleaning utensils, such as the dental cleaning brush, are used to remove plaque.",
    "Toothbrushes are essential dental care tools for ensuring oral hygiene.",
    "Using a tooth hygiene tool and dental care implement promotes good oral health.",
    "Dental brushes with bristles are used for cleaning teeth and maintaining oral hygiene.",
    "Toothbrushes and teeth grooming tools are important for maintaining dental health.",
    "Dental cleaning brushes, along with tooth care bristles, help in maintaining oral hygiene.",
    "Teeth brushing devices, like the dental care tool, are used for daily oral care.",
    "Tooth scrubbers are effective dental hygiene instruments for keeping the mouth clean.",
    "Using a teeth implement and tooth cleaning bristle is essential for proper oral hygiene.",
    "A tooth cleaning instrument and dental hygiene brush are used for oral care routines.",
    "Tooth polishers and dental scrubbers contribute to maintaining good oral health.",
    "Teeth cleaning brushes, along with dental cleaning utensils, are used for oral hygiene.",
    "Toothbrushes, dental grooming tools, and teeth cleaning bristles help maintain oral hygiene.",
    "Using tooth implements and dental care brushes is crucial for oral health.",
    "Dental hygiene instruments, like teeth hygiene utensils, are important for oral care routines.",
    "Toothbrushes with bristles are used for cleaning teeth and promoting oral hygiene.",
    "Using dental tools and teeth care implements is necessary for maintaining good oral health.",
    "A tooth cleaning brush, along with dental hygiene utensils, ensures proper oral care.",
    "Dental cleaning instruments, like teeth hygiene brushes, are essential for oral hygiene.",
    "Tooth polishers and dental grooming tools are used for maintaining healthy teeth and gums.",
    "Teeth cleaning utensils, such as dental cleaning brushes, are vital for oral care routines.",
    "Toothbrushes are indispensable dental care tools for ensuring proper oral hygiene.",
    "Using tooth hygiene tools and dental care implements promotes good oral health.",
    "Dental brushes with bristles are used for cleaning teeth and ensuring oral hygiene.",
    "Toothbrushes and teeth grooming tools play a crucial role in maintaining dental health.",
    "Dental cleaning brushes, along with tooth care bristles, help in achieving optimal oral hygiene.",
    "Teeth brushing devices, like dental care tools, are used for daily oral care routines.",
    "Tooth scrubbers are effective dental hygiene instruments for keeping the mouth fresh and clean.",
    "Using teeth implements and tooth cleaning bristles is essential for maintaining oral hygiene.",
    "A tooth cleaning instrument and dental hygiene brush are essential for oral care.",
    "Tooth polishers and dental scrubbers contribute significantly to maintaining good oral health.",
    "Teeth cleaning brushes, along with dental cleaning utensils, are necessary for oral hygiene.",
    "Toothbrushes, dental grooming tools, and teeth cleaning bristles are vital for oral hygiene.",
    "Using tooth implements and dental care brushes is crucial for maintaining oral health.",
    "Dental hygiene instruments, like teeth hygiene utensils, are important for oral care routines.",
    "Toothbrushes with bristles are used for cleaning teeth and promoting optimal oral hygiene.",
    "Using dental tools and teeth care implements is necessary for maintaining good oral health.",
    "A tooth cleaning brush, along with dental hygiene utensils, ensures proper oral care.",
    "Dental cleaning instruments, like teeth hygiene brushes, are essential for maintaining oral hygiene.",
    "Tooth polishers and dental grooming tools play a key role in maintaining healthy teeth andgums.",
    "Teeth cleaning utensils, such as dental cleaning brushes, are vital for effective oral care routines.",
    "Toothbrushes are indispensable dental care tools for ensuring proper oral hygiene.",
    "Using tooth hygiene tools and dental care implements promotes good oral health.",
    "Dental brushes with bristles are used for cleaning teeth and ensuring optimal oral hygiene.",
    "Toothbrushes and teeth grooming tools play a crucial role in maintaining dental health.",
    "Dental cleaning brushes, along with tooth care bristles, help in achieving optimal oral hygiene.",
    "Teeth brushing devices, like dental care tools, are used for daily oral care routines.",
    "Tooth scrubbers are effective dental hygiene instruments for keeping the mouth fresh and clean.",
    "Using teeth implements and tooth cleaning bristles is essential for maintaining oral hygiene.",
    "A tooth cleaning instrument and dental hygiene brush are essential for oral care routines.",
    "Tooth polishers and dental scrubbers contribute significantly to maintaining good oral health.",
    "Teeth cleaning brushes, along with dental cleaning utensils, are necessary for effective oral hygiene.",
    "Toothbrushes, dental grooming tools, and teeth cleaning bristles are vital for oral hygiene.",
    "Using tooth implements and dental care brushes is crucial for maintaining oral health.",
    "Dental hygiene instruments, like teeth hygiene utensils, are important for oral care routines.",
    "Toothbrushes with bristles are used for cleaning teeth and promoting optimal oral hygiene.",
    "Using dental tools and teeth care implements is necessary for maintaining good oral health.",
    "A tooth cleaning brush, along with dental hygiene utensils, ensures proper oral care.",
    "Dental cleaning instruments, like teeth hygiene brushes, are essential for maintaining oral hygiene.",
    "Tooth polishers and dental grooming tools play a key role in maintaining healthy teeth and gums.",
    "Teeth cleaning utensils, such as dental cleaning brushes, are vital for effective oral care routines.",
    "Toothbrushes are indispensable dental care tools for ensuring proper oral hygiene.",
    "Using tooth hygiene tools and dental care implements promotes good oral health.",
    "Dental brushes with bristles are used for cleaning teeth and ensuring optimal oral hygiene.",
    "Toothbrushes and teeth grooming tools play a crucial role in maintaining dental health.",
    "Dental cleaning brushes, along with tooth care bristles, help in achieving optimal oral hygiene.",
    "Teeth brushing devices, like dental care tools, are used for daily oral care routines.",
    "Tooth scrubbers are effective dental hygiene instruments for keeping the mouth fresh and clean.",
    "Using teeth implements and tooth cleaning bristles is essential for maintaining oral hygiene.",
    "A tooth cleaning instrument and dental hygiene brush are essential for oral care routines.",
    "Tooth polishers and dental scrubbers contribute significantly to maintaining good oral health.",
    "Teeth cleaning brushes, along with dental cleaning utensils, are necessary for effective oral hygiene.",
    "Toothbrushes, dental grooming tools, and teeth cleaning bristles are vital for oral hygiene.",
    "Using tooth implements and dental care brushes is crucial for maintaining oral health.",
    "Dental hygiene instruments, like teeth hygiene utensils, are important for oral care routines.",
    "Toothbrushes with bristles are used for cleaning teeth and promoting optimal oral hygiene.",
    "Using dental tools and teeth care implements is necessary for maintaining good oral health.",
    "A tooth cleaning brush, along with dental hygiene utensils, ensures proper oral care.",
    "Dental cleaning instruments, like teeth hygiene brushes, are essential for maintaining oral hygiene.",
    "Tooth polishers and dental grooming tools play a key role in maintaining healthy teeth and gums.",
    "Teeth cleaning utensils, such as dental cleaning brushes, are vital for effective oral care routines.",
    "Toothbrushes are indispensable dental care tools for ensuring proper oral hygiene.",
    "Using tooth hygiene tools and dental care implements promotes good oral health.",
    "Dental brushes with bristles are used for cleaning teeth and ensuring optimal oral hygiene.",
    "Toothbrushes and teeth grooming tools play a crucial role in maintaining dental health.",
    "Dental cleaning brushes, along with tooth care bristles, help in achieving optimal oral hygiene.",
    "Teeth brushing devices, like dental care tools, are used for daily oral care routines.",
    "Tooth scrubbers are effective dental hygiene instruments for keeping the mouth fresh and clean.",
    "Using teeth implements and tooth cleaning bristles is essential for maintaining oral hygiene.",
    "A tooth cleaning instrument and dental hygiene brush are essential for oral care routines.",
    "Tooth polishers and dental scrubbers contribute significantly to maintaining good oral health.",
    "Teeth cleaning brushes, along with dental cleaning utensils, are necessary for effective oral hygiene.",
    "Toothbrushes, dental grooming tools, and teeth cleaning bristles are vital for oral hygiene.",
    "Using tooth implements and dental care brushes is crucial for maintaining oral health."
]
descriptions = descriptions + ["This is a photo of " + keyword for keyword in keywords]
descriptions = descriptions + ["This is " + keyword for keyword in keywords]